Feature lattice predicates
LeMonADE-project/LeMonADE pull request #87
Opened 2018-02-28 13:40 UTC by tonimueller

Recently, I need to have the monomer ID on the lattice edge for a reaction mechanism. 
For that purpose I wrote the feature FeatureExcludedVolumeIdOnLattice.h which uses a predicate as template parameter. The predicates are specified within the LatticePredicate.h and up to now, there are four functors which can be passed to the feature. 
Of course, the feature has a test :-)

2018-11-26 12:06 UTC, MartinWenge requested changes
Nice feature, I really like the additions to UpdaterAbstractCreate :+1: 

Please check the renaming of the readBreaks class, I would prefere it.

I passed all the tests and my own tool work with this version. Go for it :o)

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +void ReadBreaks<IngredientsType>::execute()
To be more precise and comparable to ReadAddBonds/WriteRemoveBonds I really prefere to rename these classes
```suggestion
void ReadRemoveBonds<IngredientsType>::execute()
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +class ReadBreaks: public ReadToDestination < IngredientsType >
```suggestion
class ReadRemoveBonds: public ReadToDestination < IngredientsType >
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> + * @class ReadBreaks
```suggestion
 * @class ReadRemoveBonds
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +	ReadBreaks(IngredientsType& destination):ReadToDestination< IngredientsType > (destination){}
```suggestion
	ReadRemoveBonds(IngredientsType& destination):ReadToDestination< IngredientsType > (destination){}
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +  std::cout << "ReadBreaks:execute() : updating " <<std::endl;
```suggestion
  std::cout << "ReadRemoveBonds:execute() : updating " <<std::endl;
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +      errormessage<<"ReadBreaks<IngredientsType>::execute()\n"
```suggestion
      errormessage<<"ReadRemoveBonds<IngredientsType>::execute()\n"
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/core/MoleculesRead.h
> +  std::cout << "ReadBreaks:execute() : done " <<std::endl;
```suggestion
  std::cout << "ReadRemoveBonds:execute() : done " <<std::endl;
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/feature/FeatureMoleculesIO.h
> +	fileReader.registerRead("!remove_bonds", new  ReadBreaks< IngredientsType > (destination) );
```suggestion
	fileReader.registerRead("!remove_bonds", new  ReadRemoveBonds< IngredientsType > (destination) );
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/feature/FeatureMoleculesIOUnsaveCheck.h
> +	fileReader.registerRead("!remove_bonds", new  ReadBreaks< IngredientsType > (destination) );
```suggestion
	fileReader.registerRead("!remove_bonds", new  ReadRemoveBonds< IngredientsType > (destination) );
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/utility/LatticePredicates.h
> +#endif
adding newline to eof
```suggestion
#endif

```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/utility/LatticePredicates.h
> + * @details Thie functor writes on the first two bits the attribute and on the remaining bits the monomer id.
just a typo
```suggestion
 * @details This functor writes on the first two bits the attribute and on the remaining bits the monomer id.
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/updater/UpdaterAbstractCreate.h
> +	//check the new bondvector bewten the new monomer and indexB
just a typo
```suggestion
	//check the new bondvector between the new monomer and indexB
```

2018-11-26 12:06 UTC, MartinWenge commented on include/LeMonADE/updater/UpdaterAbstractCreate.h
> + * @brief function to add a new monomer two already existing ones.
Can you add in this comment, that all monomers are supposed to be connected afterwards

2018-11-26 13:30 UTC, tonimueller reviewed
Changed the comment for the function 'addMonomerInsideConnectedPair'

2018-11-26 13:30 UTC, tonimueller commented on include/LeMonADE/updater/UpdaterAbstractCreate.h
> + * @brief function to add a new monomer two already existing ones.
```suggestion
 * @brief function to add a new monomer to two already existing ones such that all three monomers are connected.
```

2018-11-26 13:30 UTC, tonimueller commented on include/LeMonADE/updater/UpdaterAbstractCreate.h
> + * @brief function to add a new monomer two already existing ones.
```suggestion
 * @brief function to add a new monomer to two already existing ones such that all three are connected afterwards
```

2018-11-26 13:35 UTC, tonimueller commented
I accepted all changes and the pull request can be closed I think

2018-11-27 09:15 UTC, MartinWenge approved these changes

2018-11-27 09:17 UTC, merged